config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :profiles

  get 'profiles/new'
  post 'profiles/new'

  get 'static_pages/home'

  root 'static_pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :nickname, presence: true, length: {maximum: 50}
  validates :firstname, length: {maximum: 50}
  validates :lastname, length: {maximum: 50}
  validates :country, length: {maximum: 50}
  validates :user_id, presence: true

  has_attached_file :userpic
  validates_attachment :userpic, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(User)
      if current_user.profile.nil?
        new_profile_path
      else
        super
      end
    else
      super
    end
  end

  private
    def set_locale
      I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:edit, :update, :show]

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      flash[:success] = I18n.t('profile_created')
      redirect_to root_path
    else
      render 'static_pages/home'
    end
  end

  def edit
  end

  def show
  end

  def update
    @profile.update(profile_params)
    redirect_to root_path
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:firstname, :lastname, :country, :userpic, :use_gravatar, :nickname)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = Starterkit::Application.config.title
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def userpic_for(user, options = { size: 80})
    if !user.profile.nil?
      if user.profile.use_gravatar?
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.profile.nickname, class: "gravatar img-rounded")
      else
        size = options[:size]
        image_tag(user.profile.userpic.url, alt: user.profile.nickname, height: size, width: size, class: "gravatar img-rounded img-responsive")
      end
    end

  end

  def nickname_for(user)
    if !user.profile.nil?
      user.profile.nickname
    else
      "Unnamed"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_favicon.html.erb
<% %w(76 120 152 180).each do |size| %>
    <%= favicon_link_tag "logo.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<% %w(16 32).each do |size| %>
    <%= favicon_link_tag "logo_small.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>
<!-- link rel="shortcut icon" href="http://swiftbook.ru/favicon.ico" type="image/vnd.microsoft.icon" / -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t('about'),   '#' %></li>
      <li><%= link_to t('contacts'), '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <!-- div class="navbar-inner" -->
    <div class="container">
      <div class="navbar-header">
        <div class="navbar-brand">
          <%= link_to Starterkit::Application.config.title, root_path, id: "logo" %>
        </div>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <!--ul class="nav nav-pills pull-right" -->
          <li><%= link_to root_path, id: "HomeLnk" do%>
                <i class="glyphicon glyphicon-home" aria-hidden="true"></i>
                <%= t('home') %>
                <% end %>
                </li>
          <% if signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= userpic_for(current_user, size: 20) %><%= nickname_for(current_user) %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t('settings'), edit_user_registration_path, id: "SettingsLnk" %></li>
                  <% if !current_user.profile.nil? %>
                      <li><%= link_to t('profile'), edit_profile_path(current_user.profile.id), id: "EditProfile" %></li>
                  <% else %>
                    <li><%= link_to t('create_profile'), profiles_new_path, id: "CrProfileMnu" %></li>
                  <% end %>
                  <% if current_user.admin? %>
                      <li><%= link_to t('admin_panel'), rails_admin_path %></li>
                  <% end %>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t('signout'), destroy_user_session_path, method: "delete", id: "SignOutLnk" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li>
                <%= link_to t('signin'), "#sign_in", "data-toggle" => "modal" %>
              </li>
          <% end %>
        </ul>
      </nav>
      </div>
    </div>
  <!-- /div -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/favicon' %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<% if !signed_in? %>
  <%= render 'shared/sign_in' %>
<% end %>
<div class="container">
  <div class="bs3-row">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</div>
</body>
</html>

app/views/layouts/errors.html.erb
<h1>Ooops!</h1>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.input :nickname, label: t('nick') %>
    <%= f.input :firstname, label: t('firstname') %>
    <%= f.input :lastname, label: t('lastname') %>
    <%= f.input :country, label: t('country') %>

    <%= userpic_for(current_user) %>

    <%= f.label t('image'), class: "control-label" %>
    <%= f.file_field :userpic, class: "form-control" %>
    <%= f.input :use_gravatar, as: :boolean, label: t('use')+" Gravatar" %>

    <%= f.submit t('save_changes'), class: "btn btn-large btn-primary", id: "SaveBtn" %>
<% end %>

app/views/profiles/edit.html.erb
<% provide(:title, t('profile')) %>

<%= render 'form' %>

app/views/profiles/new.html.erb
<% provide(:title, t('profile')) %>

<%= render 'form' %>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_sign_in.html.erb
<div class="modal fade in" id="sign_in">
  <div class="modal-dialog" role="document">
  <div class="modal-content">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">x</button>
    <h2><%= t('signin') %></h2>
  </div>

  <div class="modal-body">
    <%= simple_form_for(User.new, url: session_path(:user)) do |f| %>
        <div class="form-inputs">
          <%= f.input :email, required: false, autofocus: true, input_html: { id: "user_email_input" } %>
          <%= f.input :password, required: false, input_html: { id: "user_password_input" } %>
          <%= f.input :remember_me, as: :boolean if Devise.mappings[:user].rememberable? %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, t('login') %>
        </div>
    <% end %>

    <%= link_to "Forgot your password?", new_password_path(:user) %><br />
  </div>
  </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>
    <div class="row">
      <div class="jumbotron center">
        <h1>Hello, <%= nickname_for(current_user) %>!</h1>

        <% if current_user.profile.nil? %>
          <%= link_to t('create_profile'), profiles_new_path,
                      class: "btn btn-large btn-primary", id: "create_profile" %>

        <% end %>
      </div>
    </div>
<% else %>
    <div class="row">
      <div class="jumbotron center">
        <h1><%= t('welcome') %><%= Starterkit::Application.config.title %>!</h1>

        <%= link_to t('signup_now'), new_user_registration_path,
                    class: "btn btn-large btn-primary", id: "signup" %>
      </div>

    </div>
<% end %>